services:
  quiz-app:
    image: teebow1e/go-ctf-quiz
    env_file: .env
    ports:
      - "7000:${PORT}"
    volumes:
      - ./question.json:/app/question.json
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - CTFD_URL=${CTFD_URL}
